# Generated by Django 4.2.7 on 2025-05-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadoviaje',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='viaje.viaje')),
            ],
            options={
                'verbose_name': 'Estado de Viaje',
                'verbose_name_plural': 'Estados de Viajes',
                'db_table': 'estadoviaje',
            },
        ),
    ]
