# Generated by Django 4.2.7 on 2025-05-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadoviaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoviaje',
            options={'verbose_name': 'Estado de Viaje', 'verbose_name_plural': 'Estados de Viaje'},
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='fecha_cambio',
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='nombre_estado',
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='viaje',
        ),
        migrations.AddField(
            model_name='estadoviaje',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
            preserve_default=False,
        ),
    ]
