# Generated by Django 4.2.7 on 2025-05-17 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoviaje', '0002_alter_estadoviaje_options_and_more'),
        ('carga', '0002_rename_peso_kg_carga_peso_toneladas_and_more'),
        ('destinatariofinal', '0002_remove_destinatariofinal_carga_and_more'),
        ('vehiculo', '0002_vehiculo_conductor_alter_vehiculo_empresa'),
        ('cliente', '0002_remove_cliente_correo_remove_cliente_documento_and_more'),
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_llegada',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 20, 10, 21, 183302, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 20, 10, 38, 936051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_carga',
            field=models.ForeignKey(db_column='id_carga', default=1, on_delete=django.db.models.deletion.PROTECT, to='carga.carga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_destinatario',
            field=models.ForeignKey(db_column='id_destinatario', default=1, on_delete=django.db.models.deletion.PROTECT, to='destinatariofinal.destinatariofinal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.PROTECT, to='estadoviaje.estadoviaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', default=1, on_delete=django.db.models.deletion.PROTECT, to='vehiculo.vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tiempo_estimado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
