services:
  # Comenta este servicio cuando quieras usar solo la base de datos remota
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: transporte_db
      MYSQL_USER: transporte_user
      MYSQL_PASSWORD: transporte_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"  # Cambiado de 3306:3306 a 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-transporte_db}
      - DB_USER=${DB_USER:-transporte_user}
      - DB_PASSWORD=${DB_PASSWORD:-transporte_password}
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:4200:4200"
    command: bash -c "cd /app/transporte-frontend && npm install --force && ng serve --host 0.0.0.0 --disable-host-check"
    depends_on:
      - backend

volumes:
  mysql_data:
