# Generated by Django 4.2.7 on 2025-05-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatariofinal',
            fields=[
                ('id_destinatario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='carga.carga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Destinatario Final',
                'verbose_name_plural': 'Destinatarios Finales',
                'db_table': 'destinatariofinal',
            },
        ),
    ]
