# Generated by Django 4.2.7 on 2025-05-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinatariofinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatariofinal',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='destinatariofinal',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='destinatariofinal',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='destinatariofinal',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='destinatariofinal',
            name='nombre',
        ),
        migrations.AddField(
            model_name='destinatariofinal',
            name='nombre_empresa',
            field=models.CharField(default='Empresa Destinataria - Pendiente', max_length=200),
            preserve_default=False,
        ),
    ]
