# Generated by Django 4.2.7 on 2025-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='Transferencia bancaria', max_length=50),
            preserve_default=False,
        ),
    ]
