# Generated by Django 4.2.7 on 2025-05-17 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='licencia',
            new_name='licencia_conduccion',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='direccion',
            field=models.CharField(default='Dirección pendiente de actualizar', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(default=datetime.datetime(2026, 5, 17, 18, 20, 20, 555992, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
