# Generated by Django 4.2.7 on 2025-05-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('valores_anteriores', models.TextField(blank=True, null=True)),
                ('valores_nuevos', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
            },
        ),
    ]
