# Generated by Django 4.2.7 on 2025-05-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
        ('empresa', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(blank=True, db_column='id_conductor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='conductor.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='empresa.empresa'),
        ),
    ]
