# Generated by Django 4.2.7 on 2025-05-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_carga', models.CharField(max_length=100)),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='viaje.viaje')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'db_table': 'carga',
            },
        ),
    ]
