# Generated by Django 4.2.7 on 2025-05-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='peso_kg',
            new_name='peso_toneladas',
        ),
        migrations.RemoveField(
            model_name='carga',
            name='valor_declarado',
        ),
        migrations.RemoveField(
            model_name='carga',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='carga',
            name='volumen_m3',
        ),
        migrations.AddField(
            model_name='carga',
            name='precio_por_tonelada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carga',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
