# Generated by Django 4.2.7 on 2025-05-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLoginusuarios',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_login', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_logout', models.DateTimeField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('navegador', models.CharField(max_length=255)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('exito_login', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Login',
                'verbose_name_plural': 'Auditorías de Logins',
                'db_table': 'auditoria_loginusuarios',
            },
        ),
    ]
